image: vcubus/node:latest

pipelines:
  branches:
    master:
      - step:
          name: Deploy
          deployment: production
          caches:
            - yarn
          script:
            - echo VUE_APP_API_URL=$API_URL > .env
            - yarn install
            - yarn build
            - rsync -rltvz --delete --chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r --no-perms -O dist/ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/$BITBUCKET_DEPLOYMENT_ENVIRONMENT
definitions:
  caches:
    yarn: node_modules
